name: numpy-tutorials
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - matplotlib
  - pandas 
  - pytest
  - nbval
  - statsmodels
  - pip
  - imageio
  - pooch
  - pip:
    - jupyter-book
    - gym[atari,accept-rom-license]
